stages:
  - lint
  - test
  - cleanup
  - build
  - deploy

variables:
  CADDY_IMAGE_NAME: registry.gitlab.com/nikita-sandbox/caddy:master
  FINAL_API_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

Run Lint:
  stage: lint
  tags:
    - go
  script:
    # Install golint
    - /usr/local/go/bin/go get -u golang.org/x/lint/golint
    # Run golint
    - /home/gitlab-runner/go/bin/golint -set_exit_status ./...

Run Tests:
  stage: test
  tags:
    - go
  script:
    # Run tests
    - CGO_ENABLED=0 /usr/local/go/bin/go test -v ./...

Cleanup Unused Docker Images:
  stage: cleanup
  tags:
    - docker
  script:
    # Remove unused images
    - docker image prune -f

Build Docker:
  stage: build
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    # Build API image
    - FINAL_API_IMAGE_NAME=$FINAL_API_IMAGE_NAME docker-compose build
    # Push API image
    - docker push $FINAL_API_IMAGE_NAME

Deploy to Prod:
  stage: deploy
  only:
    - master
  tags:
    - deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    # Pull API image
    - docker pull $FINAL_API_IMAGE_NAME
    # Pull Caddy image
    - docker pull $CADDY_IMAGE_NAME
    # Start API
    - FINAL_API_IMAGE_NAME=$FINAL_API_IMAGE_NAME
      CADDY_IMAGE_NAME=$CADDY_IMAGE_NAME
      CLOUDFLARE_API_KEY=$CLOUDFLARE_API_KEY
      docker-compose up
      --remove-orphans
      -d api
    # Reload caddy's config file and gracefully restart caddy
    - docker kill --signal="USR1" caddy
    # Remove unused images
    - docker image prune -f
